pipeline {
	agent any
	stages {
		stage('Maven Compile'){
			steps{
					echo 'Project compile stage'
					bat label: 'compilation running', script: '''mvn compile'''
			}
		}

		stage('Unit Test'){
			steps{
					echo 'Project compile stage'
					bat label: 'compilation running', script: '''mvn test'''
			}
		}

		stage('Maven Package'){
			steps{
					echo 'Project compile stage'
					bat label: 'compilation running', script: '''mvn package'''
			}
		}
	}
}